### ISSUE TITLE
shows object has no attribute 'convert_and_load_onnx_model'

### ISSUE THREAD

**Issue by pradeepdev-1995** [Shivanandroy/simpleT5#16]
Shows the error AttributeError: 'SimpleT5' object has no attribute 'convert_and_load_onnx_model' while running the example notebook provided in the repository

https://github.com/Shivanandroy/simpleT5/blob/main/examples/simpleT5-summarization.ipynb

**Comment by Shivanandroy** [comment]
Hi @pradeepdev-1995 , Thanks for pointing out, I have updated the notebook. The recent version of simpleT5 only supports below methods
```python
# import
from simplet5 import SimpleT5

# instantiate
model = SimpleT5()

# load (supports t5, mt5, byT5 models)
model.from_pretrained("t5","t5-base")

# train
model.train(train_df=train_df, # pandas dataframe with 2 columns: source_text & target_text
            eval_df=eval_df, # pandas dataframe with 2 columns: source_text & target_text
            source_max_token_len = 512, 
            target_max_token_len = 128,
            batch_size = 8,
            max_epochs = 5,
            use_gpu = True,
            outputdir = "outputs",
            early_stopping_patience_epochs = 0,
            precision = 32
            )

# load trained T5 model
model.load_model("t5","path/to/trained/model/directory", use_gpu=False)

# predict
model.predict("input text for prediction")
```

**Comment by pradeepdev-1995** [comment]
@Shivanandroy  Thank you
Which means **convert_and_load_onnx_model** is no longer available?
If I want to export a model to onnx for faster inference then what should I do?

**Comment by Shivanandroy** [comment]
There are many packages which can help you with quantization and onnx runtime. e.g. fastT5: https://github.com/Ki6an/fastT5

**Comment by pradeepdev-1995** [comment]
Thank you
