### ISSUE TITLE
Is the task string necessary?

### ISSUE THREAD

**Issue by nikogamulin** [Shivanandroy/simpleT5#2]
Hi,

I have fine-tuned the model to write a compliment for a person, given the person's profile and it works pretty well. In the training examples, I haven't prepended the string 'summarize :' to the source_string column entries. Is it necessary (does it lead to better results) to prepend the string indicating the task?

**Comment by Shivanandroy** [comment]
For fine-tuning T5 model, “prefix”, to assist with multi-task training . In you case, as you are training on single task, so the prefix is not necessary.

Based on my experiments, I found that if you training for a task which T5 was pretrained in, for e.g. summarization or translation, adding a prefix, might make sense as it is going to converge slightly faster. That's it. But no impact on the results.
