### ISSUE TITLE
Suppress the Output Models

### ISSUE THREAD

**Issue by bayismet** [Shivanandroy/simpleT5#21]
Hello there!

I'd like to ask if there is any possible way to eliminate all models, except for the last trained one. When I fine tune a model, it gives me X different models if I fine tune the model X epochs. I just need the last model and couldn't find a way to prevent writing those models to disk.

Thanks!

**Comment by pashok3d** [comment]
You need to add `ModelCheckpoint` callback with `k=1` [here](https://github.com/Shivanandroy/simpleT5/blob/94ad898c428f48d13cb40d0acd237198475e80b3/simplet5/simplet5.py#L364).

**Comment by Shivanandroy** [comment]
@bayismet Sorry for late reply, you can save the model at the last epoch in the latest release
you can use `save_only_last_epoch=True`  in `.train` method.
```
# import
from simplet5 import SimpleT5

# instantiate
model = SimpleT5()

# load (supports t5, mt5, byT5 models)
model.from_pretrained("t5","t5-base")

# train
model.train(train_df=train_df
            eval_df=eval_df,
            source_max_token_len = 512, 
            target_max_token_len = 128,
            batch_size = 8,
            max_epochs = 5,
            use_gpu = True,
            outputdir = "outputs",
            save_only_last_epoch=True
            )
```

**Comment by bayismet** [comment]
Better late than never!

Thanks for the answer, I'll submit is as closed now.

**Comment by bayismet** [comment]
Sorry buy I have to reopen it. I was already installed simplet5 via pip. So I updated it by using the following command:

`%pip install simplet5 -U`

Then I tried the following code:

`# import
from simplet5 import SimpleT5

# instantiate
model = SimpleT5()

# load (supports t5, mt5, byT5 models)
model.from_pretrained("t5", "t5-base")

model.train(train_df=df,
            eval_df=df,
            source_max_token_len=512,
            target_max_token_len=128,
            batch_size=8,
            max_epochs=5,
            use_gpu=True,
            outputdir="outputs",
            save_only_last_epoch=True
)
`

But it gives the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-0a3e541f21d2> in <module>
      8 model.from_pretrained("t5", "t5-base")
      9 
---> 10 model.train(train_df=df,
     11             eval_df=df,
     12             source_max_token_len=512,

TypeError: train() got an unexpected keyword argument 'save_only_last_epoch'

Thanks.

**Comment by bayismet** [comment]
Tried it again, I can confirm that property is working. Closing the issue now. Thanks!
